### ISSUE TITLE
Icon disappears from Firefox

### ISSUE THREAD

**Issue by CaptainKarma** [BlackYoup/outlook-notifier#17]
Hi,

I found an issue with the latest Outlook Notifier 1.2.1 and Firefox 37.0.2

If I change Firefox settings from;
History -> Firefox will: Remember History
to;
History -> Firefox will: Never Remember History

The Outlook icon disappears from the Toolbar.

Cheers

**Comment by BlackYoup** [comment]
Hi,

Yes, this seems normal since it's acting like the "Private browsing" feature. In this mode, addons without permissions are restricted (https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing)

I'm not sure how I'm supposed to deal with this since I wouldn't expect this addon to be useful in private browsing.

Any thoughts ?

**Comment by CaptainKarma** [comment]
Hi,

Has it always been like that?  I've not seen it before but then maybe I didn't use that setting.  I didn't appreciate that it was basically Private browsing.

Feel free to close this Issue, I thought it was a bug :)

Cheers

**Comment by BlackYoup** [comment]
This is possible that before this update it worked even with this setting. But OS X users had problem with the icon (the counter part was broken) and I had to use the "recommended" way to fix it, it might be a side effect :/

Anyways, thanks for the report, I'll keep this in mind if someone else has this issue :)
